package com.patient.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(
        name = "patients",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = "aadharCard"),
                @UniqueConstraint(columnNames = "mobile"),
                @UniqueConstraint(columnNames = "email")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"patientId"}) // Don't log full UUID in toString
public class Patient {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String patientId;  // UUID will be auto-generated by DB or @PrePersist

    @Column(nullable = false, length = 100)
    private String fullName;

    @Column(nullable = false, unique = true, length = 10)
    private String mobile;

    @Column(nullable = false, unique = true, length = 100)
    private String email;

    @Column(nullable = false, length = 10)
    private String gender;

    private LocalDate dateOfBirth;

    private String address;
    private String city;
    private String state;

    @Column(length = 6)
    private String pincode;

    @Column(nullable = false, unique = true, length = 12)
    private String aadharCard;

    @Column(name = "is_active", nullable = false)
    private boolean isActive = false;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "created_by", length = 50)
    private String createdBy;

    @Column(name = "updated_by", length = 50)
    private String updatedBy;

    @PrePersist
    private void ensureId() {
        if (this.patientId == null) {
            this.patientId = UUID.randomUUID().toString();
        }
    }
}