package com.patient.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.util.UUID;

@Entity
@Table(
        name = "patients",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = "aadharCard"),
                @UniqueConstraint(columnNames = "mobile"),
                @UniqueConstraint(columnNames = "email")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"patientId"}) // Don't log full UUID in toString
public class Patient {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String patientId;  // UUID will be auto-generated by DB or @PrePersist

    @Column(nullable = false, length = 100)
    private String fullName;

    @Column(nullable = false, unique = true, length = 10)
    private String mobile;

    @Column(nullable = false, unique = true, length = 100)
    private String email;

    @Column(nullable = false, length = 10)
    private String gender;

    private LocalDate dateOfBirth;

    private String address;
    private String city;
    private String state;

    @Column(length = 6)
    private String pincode;

    @Column(nullable = false, unique = true, length = 12)
    private String aadharCard;

    // Auto-generate UUID if DB doesn't support UUID generation
    @PrePersist
    private void ensureId() {
        if (this.patientId == null) {
            this.patientId = UUID.randomUUID().toString();
        }
    }
}